"""Domain models and pure planning logic."""

from student_planner.domain.electives import (
    DEFAULT_ECTS_BY_ELECTIVE_CATEGORY,
    DIFFICULTY_RANK_BY_ELECTIVE_CATEGORY,
    ElectiveCategory,
    ElectiveIntent,
    elective_category_for_requirement_type,
)
from student_planner.domain.grades import (
    Grade,
    compare_letter_grades,
    earns_credit,
    is_letter_grade,
    is_pass_fail_grade,
    is_supported_grade,
    is_unsuccessful,
    is_withdrawal,
    normalize_grade,
    satisfies_min_grade,
)
from student_planner.domain.planning import (
    CompletedCourseAttempt,
    CourseEligibilitySummary,
    CoursePlanningStatus,
    CourseRecommendation,
    DifficultyPreference,
    InProgressCourse,
    PlanningGoal,
    PlanningReport,
    PlanningWarning,
    PlanningWarningSeverity,
    RecommendationScenario,
    RecommendationScenarioKind,
    RequirementProgress,
    RequirementProgressStatus,
    StudentPlanningInput,
    normalize_display_course_code,
)

__all__ = [
    "CompletedCourseAttempt",
    "CourseEligibilitySummary",
    "CoursePlanningStatus",
    "CourseRecommendation",
    "DifficultyPreference",
    "DEFAULT_ECTS_BY_ELECTIVE_CATEGORY",
    "DIFFICULTY_RANK_BY_ELECTIVE_CATEGORY",
    "ElectiveCategory",
    "ElectiveIntent",
    "elective_category_for_requirement_type",
    "Grade",
    "InProgressCourse",
    "PlanningGoal",
    "PlanningReport",
    "PlanningWarning",
    "PlanningWarningSeverity",
    "RecommendationScenario",
    "RecommendationScenarioKind",
    "RequirementProgress",
    "RequirementProgressStatus",
    "StudentPlanningInput",
    "compare_letter_grades",
    "earns_credit",
    "is_letter_grade",
    "is_pass_fail_grade",
    "is_supported_grade",
    "is_unsuccessful",
    "is_withdrawal",
    "normalize_display_course_code",
    "normalize_grade",
    "satisfies_min_grade",
]
